[build]
builder = "nixpacks"
buildCommand = "npm install"
buildTimeout = 600

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"

[[services]]
name = "scool-api"
port = 3000
protocol = "http"
